from __future__ import annotations

MOVIE_GENRES: dict[str, int] = {
    "action": 28,
    "adventure": 12,
    "animation": 16,
    "comedy": 35,
    "crime": 80,
    "documentary": 99,
    "drama": 18,
    "family": 10751,
    "fantasy": 14,
    "history": 36,
    "horror": 27,
    "music": 10402,
    "mystery": 9648,
    "romance": 10749,
    "science fiction": 878,
    "sci-fi": 878,
    "thriller": 53,
    "war": 10752,
    "western": 37,
}

TV_GENRES: dict[str, int] = {
    "action": 10759,
    "adventure": 10759,
    "animation": 16,
    "comedy": 35,
    "crime": 80,
    "documentary": 99,
    "drama": 18,
    "family": 10751,
    "kids": 10762,
    "mystery": 9648,
    "reality": 10764,
    "sci-fi": 10765,
    "science fiction": 10765,
    "fantasy": 10765,
    "talk": 10767,
    "war": 10768,
    "western": 37,
}

KEYWORD_HINTS: dict[str, tuple[list[str], list[int], list[str], list[int]]] = {
    "cozy": (["cozy", "heartwarming", "feel-good"], [35, 10749], [], []),
    "comfort": (["comfort", "light", "uplifting"], [35, 10751], [], []),
    "funny": (["funny", "laugh-out-loud"], [35], [], []),
    "dark": (["dark", "gritty", "intense"], [53, 9648], [], []),
    "psychological": (["psychological", "mind-bending", "twist"], [53, 9648], [], []),
    "thriller": (["thriller", "suspense"], [53], [], []),
    "mind-bending": (["mind-bending", "twist ending"], [53, 878, 9648], [], []),
    "romantic": (["romantic", "date night"], [10749, 35], [], []),
    "date night": (["romantic", "date night"], [10749, 35], [], []),
    "kids": (["kids", "family"], [10751, 16], [], [27]),
    "family": (["family", "animated"], [10751, 16], [], [27]),
    "cry": (["tearjerker", "emotional"], [18], [], []),
    "breakup": (["healing", "comfort"], [18, 35], ["romance"], [10749]),
    "horror": (["horror", "scary"], [27], [], []),
    "violent": (["violent", "gore"], [53], ["gore", "slasher"], [27]),
    "background": (["easy watch", "background"], [35, 10764], [], []),
    "slow": (["slow burn", "meditative"], [18, 9648], [], []),
}

DEFAULT_ROULETTE_GENRES: list[int] = [35, 18, 53, 878, 10749]

MOCK_CATALOG: list[dict[str, object]] = [
    {
        "id": 13,
        "media_type": "movie",
        "title": "Forrest Gump",
        "poster_path": "/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg",
        "year": 1994,
        "genres": [18, 35, 10749],
        "genre_names": ["Drama", "Comedy", "Romance"],
        "overview": "A kind-hearted man witnesses and influences defining moments in American history.",
        "vote_average": 8.5,
        "vote_count": 26000,
        "runtime": 142,
        "keywords": ["feel-good", "life journey", "comfort"],
        "cast": ["Tom Hanks", "Robin Wright"],
        "imdb_id": "tt0109830",
    },
    {
        "id": 680,
        "media_type": "movie",
        "title": "Pulp Fiction",
        "poster_path": "/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg",
        "year": 1994,
        "genres": [53, 80],
        "genre_names": ["Thriller", "Crime"],
        "overview": "Interlocking criminal stories with razor-sharp dialogue and dark humor.",
        "vote_average": 8.49,
        "vote_count": 28000,
        "runtime": 154,
        "keywords": ["dark humor", "crime", "stylized"],
        "cast": ["John Travolta", "Samuel L. Jackson"],
        "imdb_id": "tt0110912",
    },
    {
        "id": 155,
        "media_type": "movie",
        "title": "The Dark Knight",
        "poster_path": "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
        "year": 2008,
        "genres": [28, 80, 18, 53],
        "genre_names": ["Action", "Crime", "Drama", "Thriller"],
        "overview": "Batman faces the Joker in a battle that pushes Gotham to its limits.",
        "vote_average": 8.51,
        "vote_count": 34000,
        "runtime": 152,
        "keywords": ["dark", "hero", "chaos"],
        "cast": ["Christian Bale", "Heath Ledger"],
        "imdb_id": "tt0468569",
    },
    {
        "id": 27205,
        "media_type": "movie",
        "title": "Inception",
        "poster_path": "/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg",
        "year": 2010,
        "genres": [28, 878, 12],
        "genre_names": ["Action", "Science Fiction", "Adventure"],
        "overview": "A thief enters dreams to steal secrets and plants an impossible idea.",
        "vote_average": 8.37,
        "vote_count": 36000,
        "runtime": 148,
        "keywords": ["mind-bending", "dream", "twist"],
        "cast": ["Leonardo DiCaprio", "Joseph Gordon-Levitt"],
        "imdb_id": "tt1375666",
    },
    {
        "id": 603,
        "media_type": "movie",
        "title": "The Matrix",
        "poster_path": "/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
        "year": 1999,
        "genres": [28, 878],
        "genre_names": ["Action", "Science Fiction"],
        "overview": "A hacker discovers reality is a simulation and joins a rebellion.",
        "vote_average": 8.2,
        "vote_count": 25000,
        "runtime": 136,
        "keywords": ["mind-bending", "simulation", "action"],
        "cast": ["Keanu Reeves", "Carrie-Anne Moss"],
        "imdb_id": "tt0133093",
    },
    {
        "id": 862,
        "media_type": "movie",
        "title": "Toy Story",
        "poster_path": "/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg",
        "year": 1995,
        "genres": [16, 35, 10751],
        "genre_names": ["Animation", "Comedy", "Family"],
        "overview": "A cowboy doll feels threatened when a new spaceman toy arrives.",
        "vote_average": 8.0,
        "vote_count": 19000,
        "runtime": 81,
        "keywords": ["family", "kids", "friendship"],
        "cast": ["Tom Hanks", "Tim Allen"],
        "imdb_id": "tt0114709",
    },
    {
        "id": 1399,
        "media_type": "tv",
        "title": "Game of Thrones",
        "poster_path": "/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg",
        "year": 2011,
        "genres": [10765, 18, 10759],
        "genre_names": ["Sci-Fi & Fantasy", "Drama", "Action & Adventure"],
        "overview": "Noble families wage war for control of the Iron Throne.",
        "vote_average": 8.45,
        "vote_count": 24000,
        "runtime": 57,
        "keywords": ["epic", "politics", "dark"],
        "cast": ["Emilia Clarke", "Kit Harington"],
        "imdb_id": "tt0944947",
    },
    {
        "id": 2316,
        "media_type": "tv",
        "title": "The Office",
        "poster_path": "/qWnJzyZhyy74gjpSjIXWmuk0ifX.jpg",
        "year": 2005,
        "genres": [35],
        "genre_names": ["Comedy"],
        "overview": "A documentary crew follows office employees in Scranton.",
        "vote_average": 8.59,
        "vote_count": 4600,
        "runtime": 22,
        "keywords": ["comfort", "funny", "background"],
        "cast": ["Steve Carell", "John Krasinski"],
        "imdb_id": "tt0386676",
    },
    {
        "id": 1396,
        "media_type": "tv",
        "title": "Breaking Bad",
        "poster_path": "/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg",
        "year": 2008,
        "genres": [18, 80],
        "genre_names": ["Drama", "Crime"],
        "overview": "A chemistry teacher turns to meth production after a cancer diagnosis.",
        "vote_average": 8.92,
        "vote_count": 15000,
        "runtime": 47,
        "keywords": ["dark", "crime", "intense"],
        "cast": ["Bryan Cranston", "Aaron Paul"],
        "imdb_id": "tt0903747",
    },
    {
        "id": 66732,
        "media_type": "tv",
        "title": "Stranger Things",
        "poster_path": "/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
        "year": 2016,
        "genres": [18, 10765, 9648],
        "genre_names": ["Drama", "Sci-Fi & Fantasy", "Mystery"],
        "overview": "Kids uncover supernatural secrets in their small town.",
        "vote_average": 8.6,
        "vote_count": 19000,
        "runtime": 50,
        "keywords": ["mystery", "nostalgia", "supernatural"],
        "cast": ["Millie Bobby Brown", "Finn Wolfhard"],
        "imdb_id": "tt4574334",
    },
]
